[[header]]
  name = "Ren'Py"
  weight = 1
  identifier = "renpy"
  url = "/renpy/"

[[header]]
  name = "RPG Maker"
  weight = 2
  identifier = "rpg-maker"
  url = "/rpgmaker/"

[[header]]
  name = "PICO-8"
  weight = 3
  identifier = "pico8"
  url = "/pico8/"

[[header]]
  name = "Formations"
  weight = 4
  identifier = "formations"
  url = "https://fairedesjeux.fr"
  [header.params]
    class = "text-astride"

# This one isn't used due to needing a specific HTML structure, it's here only for clarity
[[header]]
  name = "GameDevAlliance.fr"
  weight = 5
  identifier = "gda"
  url = "https://gamedevalliance.fr"

[[header]]
  name = "Rejoindre le Discord"
  weight = 6
  identifier = "discord"
  url = "https://discord.gg/RrBppaj"
  [header.params]
    class = "text-purple-500"

# Default Left Sidebar menu
[[general]]
name = "Liste des portails"
weight = 20
identifier = "portails"
url = "/portails/"

# RPG Maker
[[rpgmaker]]
name = "Découvrir"
weight = 20
identifier = "decouvrir"
url = "/decouvrir/"

[[rpgmaker]]
name = "Vue d'ensemble"
weight = 25
identifier = "general"
url = "/general/"

[[rpgmaker]]
name = "Documentation"
weight = 30
identifier = "doc"
url = "/doc/"

[[rpgmaker]]
name = "Trucs et astuces"
weight = 35
identifier = "astuces"
url = "/astuces/"

[[rpgmaker]]
name = "Scripts"
weight = 40
identifier = "scripts"
url = "/scripts/"

[[rpgmaker]]
name = "L'univers du making"
weight = 45
identifier = "univers"
url = "/univers/"

# RME
[[rme]]
name = "Syntaxe"
weight = 20
identifier = "syntaxe"
url = "/syntaxe/"

[[rme]]
name = "Commandes"
weight = 25
identifier = "commandes"
url = "/commandes/"

[[rme]]
name = "Évènements enrichis"
weight = 30
identifier = "events"
url = "/events/"

[[rme]]
name = "Base de données"
weight = 35
identifier = "bdd"
url = "/bdd/"

# GameMaker
[[gamemaker]]
name = "Découvrir"
weight = 20
identifier = "decouvrir"
url = "/decouvrir/"

[[gamemaker]]
name = "Apprendre"
weight = 25
identifier = "apprendre"
url = "/apprendre/"

# Ren'Py
[[renpy]]
name = "Articles généraux"
weight = 20
identifier = "general"
url = "/general/"

[[renpy]]
name = "Scripts d'exemple"
weight = 25
identifier = "scripts"
url = "/scripts/"

# Unity
[[unity]]
name = "Apprendre"
weight = 20
identifier = "apprendre"
url = "/apprendre/"

# Graphisme
[[graphisme]]
name = "Pixel art"
weight = 20
identifier = "pixelart"
url = "/pixelart/"

# Distribution
[[distribution]]
name = "Présentation"
weight = 20
identifier = "presentation"
url = "/presentation/"

[[distribution]]
name = "Publication"
weight = 25
identifier = "publication"
url = "/publication/"

# PICO-8
[[pico-8]]
name = "Articles généraux"
weight = 20
identifier = "general"
url = "/general/"

[[pico-8]]
name = "Autres fantasy consoles"
weight = 25
identifier = "fantasy-consoles"
url = "/fantasy-consoles/"

# Gazette de l'Alliance
[[gazette]]
name = "Gazette de l'Alliance"
weight = 20
identifier = "gazette"
url = "/gazette/"

[[docs_meta]]
name = "A propos du wiki"
weight = 50
identifier = "meta"
url = "/wiki/"

[[docs_meta]]
name = "Code source"
parent = "meta"
weight = 3
url = "https://github.com/gamedevalliance/wiki"
