baseURL = "https://wiki.gamedevalliance.fr/"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "Le wiki de la création de jeux"
theme = "hugo-royal-theme"
PygmentsCodeFences = "true"
pygmentsUseClasses = "true"
smartypantsQuotesNBSP = "true"
enableGitInfo = "true"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
staticDir = ["static", "images", "videos"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[privacy]
  [privacy.youtube]
    privacyEnhanced = true

[params]
editURL = "https://github.com/gamedevalliance/wiki/edit/master/content"
removeTrailingSlash = true

[social]
twitter = "gamedevalliance"

[[menu.global]]
name = "Discord"
weight = 1
identifier = "discord"
pre = "<i class=\"icon-discord\"></i>"
url = "https://discord.gg/RrBppaj"

[[menu.global]]
name = "Facebook"
weight = 2
identifier = "facebook"
pre = "<i class=\"icon-facebook\"></i>"
url = "https://www.facebook.com/GameDevAlliance"

[[menu.global]]
name = "Twitter"
weight = 3
identifier = "twitter"
pre = "<i class=\"icon-twitter\"></i>"
url = "https://twitter.com/gamedevalliance"

[[menu.global]]
name = "Youtube"
weight = 4
identifier = "youtube"
pre = "<i class=\"icon-youtube\"></i>"
url = "https://www.youtube.com/c/GameDevAlliance"

[[menu.global]]
name = "itch.io"
weight = 5
identifier = "itchio"
pre = "<i class=\"icon-itchio\"></i>"
url = "https://gamedevalliance.itch.io"

[[menu.global]]
name = "FaireDesJeux.fr"
weight = 6
identifier = "site"
url = "https://fairedesjeux.fr/"

# Default Left Sidebar menu
[[menu.general]]
name = "Liste des portails"
weight = 20
identifier = "portails"
url = "/portails/"

# RPG Maker
[[menu.rpgmaker]]
name = "Découvrir"
weight = 20
identifier = "decouvrir"
url = "/decouvrir/"

[[menu.rpgmaker]]
name = "Mapping"
weight = 25
identifier = "mapping"
url = "/mapping/"

[[menu.rpgmaker]]
name = "Évènements"
weight = 30
identifier = "events"
url = "/events/"

[[menu.rpgmaker]]
name = "Documentation"
weight = 35
identifier = "doc"
url = "/doc/"

[[menu.rpgmaker]]
name = "Scripts"
weight = 40
identifier = "scripts"
url = "/scripts/"

[[menu.rpgmaker]]
name = "L'univers du making"
weight = 45
identifier = "univers"
url = "/univers/"

# RME
[[menu.rme]]
name = "Syntaxe"
weight = 20
identifier = "syntaxe"
url = "/syntaxe/"

[[menu.rme]]
name = "Commandes"
weight = 25
identifier = "commandes"
url = "/commandes/"

[[menu.rme]]
name = "Évènements enrichis"
weight = 30
identifier = "events"
url = "/events/"

[[menu.rme]]
name = "Base de données"
weight = 35
identifier = "bdd"
url = "/bdd/"

# GameMaker
[[menu.gamemaker]]
name = "Découvrir"
weight = 20
identifier = "decouvrir"
url = "/decouvrir/"

[[menu.gamemaker]]
name = "Apprendre"
weight = 25
identifier = "apprendre"
url = "/apprendre/"

# Ren'Py
[[menu.renpy]]
name = "Articles généraux"
weight = 20
identifier = "general"
url = "/general/"

[[menu.renpy]]
name = "Scripts d'exemple"
weight = 25
identifier = "scripts"
url = "/scripts/"

# Unity
[[menu.unity]]
name = "Apprendre"
weight = 20
identifier = "apprendre"
url = "/apprendre/"

# Graphisme
[[menu.graphisme]]
name = "Pixel art"
weight = 20
identifier = "pixelart"
url = "/pixelart/"

# Distribution

[[menu.distribution]]
name = "Présentation"
weight = 20
identifier = "presentation"
url = "/presentation/"

[[menu.distribution]]
name = "Publication"
weight = 25
identifier = "publication"
url = "/publication/"

# PICO-8
[[menu.pico-8]]
name = "Articles généraux"
weight = 20
identifier = "general"
url = "/general/"

[[menu.pico-8]]
name = "Autres fantasy consoles"
weight = 25
identifier = "fantasy-consoles"
url = "/fantasy-consoles/"

# Gazette de l'Alliance
[[menu.gazette]]
name = "Gazette de l'Alliance"
weight = 20
identifier = "gazette"
url = "/gazette/"

[[menu.docs_meta]]
name = "A propos du wiki"
weight = 50
identifier = "meta"
url = "/wiki/"

[[menu.docs_meta]]
name = "Code source"
parent = "meta"
weight = 3
url = "https://github.com/gamedevalliance/wiki"
