baseURL = "https://wiki.gamedevalliance.fr/"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "Le wiki de la création de jeux"
PygmentsCodeFences = "true"
pygmentsUseClasses = "true"
smartypantsQuotesNBSP = "true"
enableGitInfo = "true"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[privacy]
  [privacy.youtube]
    privacyEnhanced = true

[params]
editURL = "https://github.com/gamedevalliance/wiki/edit/master/content"
removeTrailingSlash = true

[social]
twitter = "gamedevalliance"

[module]

  [[module.mounts]]
    source = "./node_modules/typeface-muli/files"
    target = "static/fonts/"

  [[module.mounts]]
    source = "./node_modules/typeface-source-sans-pro/files"
    target = "static/fonts/"

  [[module.mounts]]
    source = "./node_modules/typeface-source-code-pro/files"
    target = "static/fonts/"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "images"
    target = "static"

  [[module.mounts]]
    source = "videos"
    target = "static"


[[menu.header]]
  name = "Ren'Py"
  weight = 1
  identifier = "renpy"
  url = "/renpy/"

[[menu.header]]
  name = "RPG Maker"
  weight = 2
  identifier = "rpg-maker"
  url = "/rpgmaker/"

[[menu.header]]
  name = "PICO-8"
  weight = 3
  identifier = "pico8"
  url = "/pico8/"

[[menu.header]]
  name = "Formations"
  weight = 4
  identifier = "formations"
  url = "https://fairedesjeux.fr"
  [menu.header.params]
    class = "text-astride"

# This one isn't used due to needing a specific HTML structure, it's here only for clarity
[[menu.header]]
  name = "GameDevAlliance.fr"
  weight = 5
  identifier = "gda"
  url = "https://gamedevalliance.fr"

[[menu.header]]
  name = "Rejoindre le Discord"
  weight = 6
  identifier = "discord"
  url = "https://discord.gg/RrBppaj"
  [menu.header.params]
    class = "text-purple-500"

# Default Left Sidebar menu
[[menu.general]]
name = "Liste des portails"
weight = 20
identifier = "portails"
url = "/portails/"

# RPG Maker
[[menu.rpgmaker]]
name = "Découvrir"
weight = 20
identifier = "decouvrir"
url = "/decouvrir/"

[[menu.rpgmaker]]
name = "Vue d'ensemble"
weight = 25
identifier = "general"
url = "/general/"

[[menu.rpgmaker]]
name = "Documentation"
weight = 30
identifier = "doc"
url = "/doc/"

[[menu.rpgmaker]]
name = "Trucs et astuces"
weight = 35
identifier = "astuces"
url = "/astuces/"

[[menu.rpgmaker]]
name = "Scripts"
weight = 40
identifier = "scripts"
url = "/scripts/"

[[menu.rpgmaker]]
name = "L'univers du making"
weight = 45
identifier = "univers"
url = "/univers/"

# RME
[[menu.rme]]
name = "Syntaxe"
weight = 20
identifier = "syntaxe"
url = "/syntaxe/"

[[menu.rme]]
name = "Commandes"
weight = 25
identifier = "commandes"
url = "/commandes/"

[[menu.rme]]
name = "Évènements enrichis"
weight = 30
identifier = "events"
url = "/events/"

[[menu.rme]]
name = "Base de données"
weight = 35
identifier = "bdd"
url = "/bdd/"

# GameMaker
[[menu.gamemaker]]
name = "Découvrir"
weight = 20
identifier = "decouvrir"
url = "/decouvrir/"

[[menu.gamemaker]]
name = "Apprendre"
weight = 25
identifier = "apprendre"
url = "/apprendre/"

# Ren'Py
[[menu.renpy]]
name = "Articles généraux"
weight = 20
identifier = "general"
url = "/general/"

[[menu.renpy]]
name = "Scripts d'exemple"
weight = 25
identifier = "scripts"
url = "/scripts/"

# Unity
[[menu.unity]]
name = "Apprendre"
weight = 20
identifier = "apprendre"
url = "/apprendre/"

# Graphisme
[[menu.graphisme]]
name = "Pixel art"
weight = 20
identifier = "pixelart"
url = "/pixelart/"

# Distribution
[[menu.distribution]]
name = "Présentation"
weight = 20
identifier = "presentation"
url = "/presentation/"

[[menu.distribution]]
name = "Publication"
weight = 25
identifier = "publication"
url = "/publication/"

# PICO-8
[[menu.pico-8]]
name = "Articles généraux"
weight = 20
identifier = "general"
url = "/general/"

[[menu.pico-8]]
name = "Autres fantasy consoles"
weight = 25
identifier = "fantasy-consoles"
url = "/fantasy-consoles/"

# Gazette de l'Alliance
[[menu.gazette]]
name = "Gazette de l'Alliance"
weight = 20
identifier = "gazette"
url = "/gazette/"

[[menu.docs_meta]]
name = "A propos du wiki"
weight = 50
identifier = "meta"
url = "/wiki/"

[[menu.docs_meta]]
name = "Code source"
parent = "meta"
weight = 3
url = "https://github.com/gamedevalliance/wiki"
