baseURL = "https://wiki.rpgmakeralliance.com/"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "Encyclopédie du making"
theme = "hugo-royal-theme"
PygmentsCodeFences = "true"
pygmentsUseClasses = "true"
smartypantsQuotesNBSP = "true"
enableGitInfo = "true"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]

[privacy]
  [privacy.youtube]
    privacyEnhanced = true

[params]
editURL = "https://github.com/rpgmakeralliance/wiki/edit/master/content"
removeTrailingSlash = true

[social]
twitter = "rpgalliance"

[[menu.global]]
name = "Discord"
weight = 1
identifier = "discord"
pre = "<i class=\"icon-discord\"></i>"
url = "https://discord.gg/RrBppaj"

[[menu.global]]
name = "Facebook"
weight = 2
identifier = "facebook"
pre = "<i class=\"icon-facebook\"></i>"
url = "https://www.facebook.com/RPGMakerAlliance"

[[menu.global]]
name = "Twitter"
weight = 3
identifier = "twitter"
pre = "<i class=\"icon-twitter\"></i>"
url = "https://twitter.com/rpgalliance"

[[menu.global]]
name = "Youtube"
weight = 4
identifier = "youtube"
pre = "<i class=\"icon-youtube\"></i>"
url = "https://youtube.com/FoxFiesta40"

[[menu.global]]
name = "Forum"
weight = 5
identifier = "forum"
url = "https://rpgmakeralliance.com/"

# Left Sidebar menu

[[menu.docs]]
name = "Découvrir RPG Maker"
weight = 20
identifier = "decouvrir"
url = "/decouvrir/"

[[menu.docs]]
name = "Graphisme"
weight = 25
identifier = "graphisme"
url = "/graphisme/"

[[menu.docs]]
name = "Évènements"
weight = 30
identifier = "events"
url = "/evenements/"

[[menu.docs]]
name = "Documentation"
weight = 35
identifier = "doc"
url = "/doc/"

[[menu.docs]]
name = "Scripts"
weight = 40
identifier = "scripts"
url = "/scripts/"

[[menu.docs]]
name = "Diffusion"
weight = 45
identifier = "diffusion"
url = "/diffusion/"

[[menu.docs]]
name = "L'univers du making"
weight = 50
identifier = "univers"
url = "/univers/"

[[menu.docs]]
name = "L'Encyclopédie"
weight = 55
identifier = "meta"
url = "/encyclopedie/"

[[menu.docs]]
name = "Code source"
parent = "meta"
weight = 3
url = "https://github.com/rpgmakeralliance/wiki"
