baseURL = "https://wiki.rpgmakeralliance.com/"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "Encyclopédie de la création de jeux"
theme = "hugo-royal-theme"
PygmentsCodeFences = "true"
pygmentsUseClasses = "true"
smartypantsQuotesNBSP = "true"
enableGitInfo = "true"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]

[privacy]
  [privacy.youtube]
    privacyEnhanced = true

[params]
editURL = "https://github.com/rpgmakeralliance/wiki/edit/master/content"
removeTrailingSlash = true

[social]
twitter = "rpgalliance"

[[menu.global]]
name = "Discord"
weight = 1
identifier = "discord"
pre = "<i class=\"icon-discord\"></i>"
url = "https://discord.gg/RrBppaj"

[[menu.global]]
name = "Facebook"
weight = 2
identifier = "facebook"
pre = "<i class=\"icon-facebook\"></i>"
url = "https://www.facebook.com/RPGMakerAlliance"

[[menu.global]]
name = "Twitter"
weight = 3
identifier = "twitter"
pre = "<i class=\"icon-twitter\"></i>"
url = "https://twitter.com/rpgalliance"

[[menu.global]]
name = "Youtube"
weight = 4
identifier = "youtube"
pre = "<i class=\"icon-youtube\"></i>"
url = "https://youtube.com/FoxFiesta40"

[[menu.global]]
name = "itch.io"
weight = 5
identifier = "itchio"
pre = "<i class=\"icon-itchio\"></i>"
url = "https://rpgmakeralliance.itch.io"

[[menu.global]]
name = "Forum"
weight = 6
identifier = "forum"
url = "https://rpgmakeralliance.com/"

# Default Left Sidebar menu
[[menu.general]]
name = "Liste des portails"
weight = 20
identifier = "portails"
url = "/portails/"

# RPG Maker
[[menu.rpgmaker]]
name = "Découvrir RPG Maker"
weight = 20
identifier = "decouvrir"
url = "/decouvrir/"

[[menu.rpgmaker]]
name = "Mapping"
weight = 25
identifier = "mapping"
url = "/mapping/"

[[menu.rpgmaker]]
name = "Évènements"
weight = 30
identifier = "events"
url = "/events/"

[[menu.rpgmaker]]
name = "Documentation"
weight = 35
identifier = "doc"
url = "/doc/"

[[menu.rpgmaker]]
name = "Scripts"
weight = 40
identifier = "scripts"
url = "/scripts/"

[[menu.rpgmaker]]
name = "L'univers du making"
weight = 45
identifier = "univers"
url = "/univers/"

# RME
[[menu.rme]]
name = "Syntaxe"
weight = 20
identifier = "syntaxe"
url = "/syntaxe/"

[[menu.rme]]
name = "Commandes"
weight = 25
identifier = "commandes"
url = "/commandes/"

[[menu.rme]]
name = "Évènements enrichis"
weight = 30
identifier = "events"
url = "/events/"

[[menu.rme]]
name = "Base de données"
weight = 35
identifier = "bdd"
url = "/bdd/"

# GameMaker
[[menu.gamemaker]]
name = "Découvrir GameMaker"
weight = 20
identifier = "decouvrir"
url = "/decouvrir/"

# Ren'Py
[[menu.renpy]]
name = "Débuter dans Ren'Py"
weight = 20
identifier = "debuter"
url = "/debuter/"

[[menu.renpy]]
name = "Progresser dans Ren'Py"
weight = 25
identifier = "progresser"
url = "/progresser/"

# Graphisme
[[menu.graphisme]]
name = "Pixel art"
weight = 20
identifier = "pixelart"
url = "/pixelart/"

# Distribution
[[menu.distribution]]
name = "Distribution"
weight = 20
identifier = "distribution"
url = "/distribution/"

# Gazette de l'Alliance
[[menu.gazette]]
name = "Gazette de l'Alliance"
weight = 20
identifier = "gazette"
url = "/gazette/"

[[menu.docs_meta]]
name = "L'Encyclopédie"
weight = 50
identifier = "meta"
url = "/encyclopedie/"

[[menu.docs_meta]]
name = "Code source"
parent = "meta"
weight = 3
url = "https://github.com/rpgmakeralliance/wiki"
